name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # (Optional) Add build steps if you’re using Jekyll, Hugo, React, etc.
      # For plain static HTML, you don’t need anything here.

      - name: Deploy to GitHub Pages
        run: echo "Deployment complete. GitHub Pages will serve directly from main branch."
